name: Changed lines
description: Get all modified lines in a Pull Request
author: "Heston Hoffman"
branding:
  icon: 'git-pull-request'
  color: 'green'
inputs:
  api_url:
    description: 'Github API URL (primarily for Github Enterprise usage)'
    required: false
    default: '${{ github.api_url }}'
  token:
    description: 'Assign a GITHUB_TOKEN to use'
    required: false
    default: '${{ github.token }}'
  branch:
    description: 'Current PR branch'
    required: false
    default: '${{ github.ref_name }}'
  repo:
    description: 'Repository to compare against'
    required: false
    default: '${{ github.repository }}'
  pr:
    description: 'Pull Request number'
    required: false
    default: '${{ github.event.number }}'
  delimiter:
    description: 'Delimiter to use for changes_files output'
    required: false
    default: ' '
  file_filter:
    description: 'Filter for file extensions to include in output. Defaults to returning all file types'
    required: false
    default: ''
outputs:
  changed_lines:
    description: 'Lines with changes'
  changed_files: 
    description: 'Files with changes'
runs:
  using: 'docker'
  image: 'Dockerfile'
