name: "Test changed lines action"
on:  
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test changed lines
        id: changed_lines
        uses: hestonhoffman/changed-lines@main
      - name: Print changed lines
        run: echo ${{ steps.changed_lines.outputs.changed_lines }}